version: '3.4'

services:
  coderwebsite:
    image: coder-website
    build:
      context: .
      dockerfile: CoderWebsite/Dockerfile
    environment:
      POSTGRES_CONNECTION_STRING: "Host=host.docker.internal;Port=5432;Database=coderdb;Username=coderuser;Password=pgpwd4coder"
      ADMIN_EMAIL: "admin@coder.ru"
      ADMIN_PASSWORD: "passwd_935806"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
  
  postgres:
    image: postgres
    container_name: postgres
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: "coderdb"
      POSTGRES_USER: "coderuser"
      POSTGRES_PASSWORD: "pgpwd4coder"
    ports:
      - "5432:5432"