version: '3.4'

services:
  coderwebsite:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
    volumes:
      - ${APPDATA}/ASP.NET/Http:/root/.aspnet/http:ro